import { ValueOf } from "@/src/shared/utils/value-of.js";

export const PERMISSIONS = {
    USER_CREATE: "USER_CREATE",
    USER_READ: "USER_READ",
    USER_UPDATE: "USER_UPDATE",
    USER_DELETE: "USER_DELETE",

    ROLE_CREATE: "ROLE_CREATE",
    ROLE_READ: "ROLE_READ",
    ROLE_UPDATE: "ROLE_UPDATE",
    ROLE_DELETE: "ROLE_DELETE",

    PERMISSION_CREATE: "PERMISSION_CREATE",
    PERMISSION_READ: "PERMISSION_READ",
    PERMISSION_UPDATE: "PERMISSION_UPDATE",
    PERMISSION_DELETE: "PERMISSION_DELETE",
} as const;

export type PERMISSIONS = ValueOf<typeof PERMISSIONS>;